In [4]:
import pandas as pd

file_path = 'C:/INTERNSHIPS/Prodigy Infotech/Task 5/US_Accidents_March23.csv'
data = pd.read_csv(file_path)
print(data)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng   End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723       NaN        NaN
1        2016-02-08 06:37:59  39.928059  -82.831184       NaN        NaN
2        2016-02-08 07:19:27  39.063148  -84.032608       NaN        NaN
3        2016-02-08 07:53:34  39.747753  -84.205582       NaN        NaN
4        2016-02-08 08:09:07  39.627781  -84.188354       NaN        NaN
...                      ...        ...         ...       ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.99888 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.76555 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.77740 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.98311 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.13736 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [8]:
missing_values=data.isnull().sum()
print(missing_values)

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  3402762
End_Lng                  3402762
Distance(mi)                   0
Description                    5
Street                     10869
City                         253
County                         0
State                          0
Zipcode                     1915
Country                        0
Timezone                    7808
Airport_Code               22635
Weather_Timestamp         120228
Temperature(F)            163853
Wind_Chill(F)            1999019
Humidity(%)               174144
Pressure(in)              140679
Visibility(mi)            177098
Wind_Direction            175206
Wind_Speed(mph)           571233
Precipitation(in)        2203586
Weather_Condition         173459
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             23246
Civil_Twilight             23246
Nautical_Twilight          23246
Astronomical_Twilight      23246
dtype: int64

In [10]:
mean_End_Lat=data['End_Lat'].mean()
data["End_Lat"].fillna(mean_End_Lat,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\2557239506.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["End_Lat"].fillna(mean_End_Lat,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829        NaN
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829        NaN
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829        NaN
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829        NaN
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829        NaN
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [11]:
mean_End_Lng=data['End_Lng'].mean()
data["End_Lng"].fillna(mean_End_Lng,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\4016878428.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["End_Lng"].fillna(mean_End_Lng,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [12]:
print(data['Description'])

0          Right lane blocked due to accident on I-70 Eas...
1          Accident on Brice Rd at Tussing Rd. Expect del...
2          Accident on OH-32 State Route 32 Westbound at ...
3          Accident on I-75 Southbound at Exits 52 52B US...
4          Accident on McEwen Rd at OH-725 Miamisburg Cen...
                                 ...
7728389                             At Market St - Accident.
7728390      At Camino Del Rio/Mission Center Rd - Accident.
7728391    At Glassell St/Grand Ave - Accident. in the ri...
7728392       At CA-90/Marina Fwy/Jefferson Blvd - Accident.
7728393                At Highland Ave/Arden Ave - Accident.
Name: Description, Length: 7728394, dtype: object

In [14]:
data['Description'] = data['Description'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\884242504.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Description'] = data['Description'].fillna(method='ffill').fillna(method='bfill')

In [15]:
missing_values=data.isnull().sum()
print(missing_values)

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                        0
End_Lng                        0
Distance(mi)                   0
Description                    0
Street                     10869
City                         253
County                         0
State                          0
Zipcode                     1915
Country                        0
Timezone                    7808
Airport_Code               22635
Weather_Timestamp         120228
Temperature(F)            163853
Wind_Chill(F)            1999019
Humidity(%)               174144
Pressure(in)              140679
Visibility(mi)            177098
Wind_Direction            175206
Wind_Speed(mph)           571233
Precipitation(in)        2203586
Weather_Condition         173459
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             23246
Civil_Twilight             23246
Nautical_Twilight          23246
Astronomical_Twilight      23246
dtype: int64

In [17]:
print(data['Street'])

0                             I-70 E
1                           Brice Rd
2                     State Route 32
3                             I-75 S
4          Miamisburg Centerville Rd
                     ...
7728389                 Pomona Fwy E
7728390                        I-8 W
7728391             Garden Grove Fwy
7728392              San Diego Fwy S
7728393                     CA-210 W
Name: Street, Length: 7728394, dtype: object

In [18]:
data['Street'] = data['Street'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\308265130.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Street'] = data['Street'].fillna(method='ffill').fillna(method='bfill')

In [19]:
print(data['City'])

0                Dayton
1          Reynoldsburg
2          Williamsburg
3                Dayton
4                Dayton
               ...
7728389       Riverside
7728390       San Diego
7728391          Orange
7728392     Culver City
7728393        Highland
Name: City, Length: 7728394, dtype: object

In [20]:
mode_city=data['City'].mode()[0]
data["City"].fillna(mode_city,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3522117575.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["City"].fillna(mode_city,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [21]:
print(data['Zipcode'])

0               45424
1          43068-3402
2               45176
3               45417
4               45459
              ...
7728389         92501
7728390         92108
7728391         92866
7728392         90230
7728393         92346
Name: Zipcode, Length: 7728394, dtype: object

In [23]:
data['Zipcode'] = data['Zipcode'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3524215152.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Zipcode'] = data['Zipcode'].fillna(method='ffill').fillna(method='bfill')

In [24]:
print(data.isnull().sum())

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                        0
End_Lng                        0
Distance(mi)                   0
Description                    0
Street                         0
City                           0
County                         0
State                          0
Zipcode                        0
Country                        0
Timezone                    7808
Airport_Code               22635
Weather_Timestamp         120228
Temperature(F)            163853
Wind_Chill(F)            1999019
Humidity(%)               174144
Pressure(in)              140679
Visibility(mi)            177098
Wind_Direction            175206
Wind_Speed(mph)           571233
Precipitation(in)        2203586
Weather_Condition         173459
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             23246
Civil_Twilight             23246
Nautical_Twilight          23246
Astronomical_Twilight      23246
dtype: int64

In [25]:
print(data['Timezone'])

0          US/Eastern
1          US/Eastern
2          US/Eastern
3          US/Eastern
4          US/Eastern
              ...
7728389    US/Pacific
7728390    US/Pacific
7728391    US/Pacific
7728392    US/Pacific
7728393    US/Pacific
Name: Timezone, Length: 7728394, dtype: object

In [26]:
mode_timezone=data['Timezone'].mode()[0]
data["Timezone"].fillna(mode_timezone,inplace=True)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3659530772.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Timezone"].fillna(mode_timezone,inplace=True)

In [27]:
print(data['Airport_Code'])

0          KFFO
1          KCMH
2          KI69
3          KDAY
4          KMGY
           ...
7728389    KRAL
7728390    KMYF
7728391    KSNA
7728392    KSMO
7728393    KSBD
Name: Airport_Code, Length: 7728394, dtype: object

In [28]:
data['Airport_Code'] = data['Airport_Code'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3134294962.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Airport_Code'] = data['Airport_Code'].fillna(method='ffill').fillna(method='bfill')

In [29]:
print(data['Weather_Timestamp'])

0          2016-02-08 05:58:00
1          2016-02-08 05:51:00
2          2016-02-08 06:56:00
3          2016-02-08 07:38:00
4          2016-02-08 07:53:00
                  ...
7728389    2019-08-23 17:53:00
7728390    2019-08-23 18:53:00
7728391    2019-08-23 18:53:00
7728392    2019-08-23 18:51:00
7728393    2019-08-23 20:50:00
Name: Weather_Timestamp, Length: 7728394, dtype: object

In [30]:
data['Weather_Timestamp'] = data['Weather_Timestamp'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3566991836.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Weather_Timestamp'] = data['Weather_Timestamp'].fillna(method='ffill').fillna(method='bfill')

In [32]:
print(data['Temperature(F)'])

0          36.9
1          37.9
2          36.0
3          35.1
4          36.0
           ...
7728389    86.0
7728390    70.0
7728391    73.0
7728392    71.0
7728393    79.0
Name: Temperature(F), Length: 7728394, dtype: float64

In [33]:
mean_temp=data['Temperature(F)'].mean()
data["Temperature(F)"].fillna(mean_temp,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\2747225543.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Temperature(F)"].fillna(mean_temp,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [34]:
print(data['Wind_Chill(F)'])

0           NaN
1           NaN
2          33.3
3          31.0
4          33.3
           ...
7728389    86.0
7728390    70.0
7728391    73.0
7728392    71.0
7728393    79.0
Name: Wind_Chill(F), Length: 7728394, dtype: float64

In [35]:
mean_wind_chill=data['Wind_Chill(F)'].mean()
data["Wind_Chill(F)"].fillna(mean_wind_chill,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\385213410.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Wind_Chill(F)"].fillna(mean_wind_chill,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [36]:
print(data['Humidity(%)'])

0           91.0
1          100.0
2          100.0
3           96.0
4           89.0
           ...
7728389     40.0
7728390     73.0
7728391     64.0
7728392     81.0
7728393     47.0
Name: Humidity(%), Length: 7728394, dtype: float64

In [37]:
mean_humidity=data['Humidity(%)'].mean()
data["Humidity(%)"].fillna(mean_humidity,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\149293324.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Humidity(%)"].fillna(mean_humidity,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [38]:
print(data['Pressure(in)'])

0          29.68
1          29.65
2          29.67
3          29.64
4          29.65
           ...
7728389    28.92
7728390    29.39
7728391    29.74
7728392    29.62
7728393    28.63
Name: Pressure(in), Length: 7728394, dtype: float64

In [39]:
mean_pressure=data['Pressure(in)'].mean()
data["Pressure(in)"].fillna(mean_pressure,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\847574928.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Pressure(in)"].fillna(mean_pressure,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [40]:
print(data['Visibility(mi)'])

0          10.0
1          10.0
2          10.0
3           9.0
4           6.0
           ...
7728389    10.0
7728390    10.0
7728391    10.0
7728392    10.0
7728393     7.0
Name: Visibility(mi), Length: 7728394, dtype: float64

In [41]:
mean_visibility=data['Visibility(mi)'].mean()
data["Visibility(mi)"].fillna(mean_visibility,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3934263335.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Visibility(mi)"].fillna(mean_visibility,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [42]:
print(data['Wind_Direction'])

0          Calm
1          Calm
2            SW
3            SW
4            SW
           ...
7728389       W
7728390      SW
7728391     SSW
7728392      SW
7728393      SW
Name: Wind_Direction, Length: 7728394, dtype: object

In [43]:
mode_wind_dir=data['Wind_Direction'].mode()[0]
data["Wind_Direction"].fillna(mode_wind_dir,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\4009634099.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Wind_Direction"].fillna(mode_wind_dir,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [44]:
print(data['Wind_Speed(mph)'])

0           NaN
1           NaN
2           3.5
3           4.6
4           3.5
           ...
7728389    13.0
7728390     6.0
7728391    10.0
7728392     8.0
7728393     7.0
Name: Wind_Speed(mph), Length: 7728394, dtype: float64

In [45]:
mean_wind_speed=data['Wind_Speed(mph)'].mean()
data["Wind_Speed(mph)"].fillna(mean_wind_speed,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3940843493.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Wind_Speed(mph)"].fillna(mean_wind_speed,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [46]:
print(data['Precipitation(in)'])

0          0.02
1          0.00
2           NaN
3           NaN
4           NaN
           ...
7728389    0.00
7728390    0.00
7728391    0.00
7728392    0.00
7728393    0.00
Name: Precipitation(in), Length: 7728394, dtype: float64

In [47]:
mean_precipitation=data['Precipitation(in)'].mean()
data["Precipitation(in)"].fillna(mean_precipitation,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\928971711.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Precipitation(in)"].fillna(mean_precipitation,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [48]:
print(data['Weather_Condition'])

0             Light Rain
1             Light Rain
2               Overcast
3          Mostly Cloudy
4          Mostly Cloudy
               ...
7728389             Fair
7728390             Fair
7728391    Partly Cloudy
7728392             Fair
7728393             Fair
Name: Weather_Condition, Length: 7728394, dtype: object

In [49]:
mode_weather_condition=data['Weather_Condition'].mode()[0]
data["Weather_Condition"].fillna(mode_weather_condition,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\1806011380.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Weather_Condition"].fillna(mode_weather_condition,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [50]:
print(data['Sunrise_Sunset'])

0          Night
1          Night
2          Night
3          Night
4            Day
           ...
7728389      Day
7728390      Day
7728391      Day
7728392      Day
7728393      Day
Name: Sunrise_Sunset, Length: 7728394, dtype: object

In [51]:
mode_sunrise_sunset=data['Sunrise_Sunset'].mode()[0]
data["Sunrise_Sunset"].fillna(mode_sunrise_sunset,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\3069298210.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Sunrise_Sunset"].fillna(mode_sunrise_sunset,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [52]:
print(data['Civil_Twilight'])

0          Night
1          Night
2          Night
3            Day
4            Day
           ...
7728389      Day
7728390      Day
7728391      Day
7728392      Day
7728393      Day
Name: Civil_Twilight, Length: 7728394, dtype: object

In [53]:
mode_civil_twilight=data['Civil_Twilight'].mode()[0]
data["Civil_Twilight"].fillna(mode_civil_twilight,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\2977619337.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Civil_Twilight"].fillna(mode_civil_twilight,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [54]:
print(data['Nautical_Twilight'])

0          Night
1          Night
2            Day
3            Day
4            Day
           ...
7728389      Day
7728390      Day
7728391      Day
7728392      Day
7728393      Day
Name: Nautical_Twilight, Length: 7728394, dtype: object

In [55]:
mode_nautical_twilight=data['Nautical_Twilight'].mode()[0]
data["Nautical_Twilight"].fillna(mode_nautical_twilight,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\279077258.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Nautical_Twilight"].fillna(mode_nautical_twilight,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [56]:
print(data['Astronomical_Twilight'])

0          Night
1            Day
2            Day
3            Day
4            Day
           ...
7728389      Day
7728390      Day
7728391      Day
7728392      Day
7728393      Day
Name: Astronomical_Twilight, Length: 7728394, dtype: object

In [57]:
mode_astronomical_twilight=data['Astronomical_Twilight'].mode()[0]
data["Astronomical_Twilight"].fillna(mode_astronomical_twilight,inplace=True)
print(data)

C:\Users\rishi\AppData\Local\Temp\ipykernel_34088\2051174920.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Astronomical_Twilight"].fillna(mode_astronomical_twilight,inplace=True)

                ID   Source  Severity           Start_Time  \
0              A-1  Source2         3  2016-02-08 05:46:00
1              A-2  Source2         2  2016-02-08 06:07:59
2              A-3  Source2         2  2016-02-08 06:49:27
3              A-4  Source2         3  2016-02-08 07:23:34
4              A-5  Source2         2  2016-02-08 07:39:07
...            ...      ...       ...                  ...
7728389  A-7777757  Source1         2  2019-08-23 18:03:25
7728390  A-7777758  Source1         2  2019-08-23 19:11:30
7728391  A-7777759  Source1         2  2019-08-23 19:00:21
7728392  A-7777760  Source1         2  2019-08-23 19:00:21
7728393  A-7777761  Source1         2  2019-08-23 18:52:06

                    End_Time  Start_Lat   Start_Lng    End_Lat    End_Lng  \
0        2016-02-08 11:00:00  39.865147  -84.058723  36.261829  -95.72557
1        2016-02-08 06:37:59  39.928059  -82.831184  36.261829  -95.72557
2        2016-02-08 07:19:27  39.063148  -84.032608  36.261829  -95.72557
3        2016-02-08 07:53:34  39.747753  -84.205582  36.261829  -95.72557
4        2016-02-08 08:09:07  39.627781  -84.188354  36.261829  -95.72557
...                      ...        ...         ...        ...        ...
7728389  2019-08-23 18:32:01  34.002480 -117.379360  33.998880 -117.37094
7728390  2019-08-23 19:38:23  32.766960 -117.148060  32.765550 -117.15363
7728391  2019-08-23 19:28:49  33.775450 -117.847790  33.777400 -117.85727
7728392  2019-08-23 19:29:42  33.992460 -118.403020  33.983110 -118.39565
7728393  2019-08-23 19:21:31  34.133930 -117.230920  34.137360 -117.23934

         Distance(mi)  ... Roundabout Station   Stop Traffic_Calming  \
0               0.010  ...      False   False  False           False
1               0.010  ...      False   False  False           False
2               0.010  ...      False   False  False           False
3               0.010  ...      False   False  False           False
4               0.010  ...      False   False  False           False
...               ...  ...        ...     ...    ...             ...
7728389         0.543  ...      False   False  False           False
7728390         0.338  ...      False   False  False           False
7728391         0.561  ...      False   False  False           False
7728392         0.772  ...      False   False  False           False
7728393         0.537  ...      False   False  False           False

        Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight  \
0                False        False          Night          Night
1                False        False          Night          Night
2                 True        False          Night          Night
3                False        False          Night            Day
4                 True        False            Day            Day
...                ...          ...            ...            ...
7728389          False        False            Day            Day
7728390          False        False            Day            Day
7728391          False        False            Day            Day
7728392          False        False            Day            Day
7728393          False        False            Day            Day

        Nautical_Twilight Astronomical_Twilight
0                   Night                 Night
1                   Night                   Day
2                     Day                   Day
3                     Day                   Day
4                     Day                   Day
...                   ...                   ...
7728389               Day                   Day
7728390               Day                   Day
7728391               Day                   Day
7728392               Day                   Day
7728393               Day                   Day

[7728394 rows x 46 columns]

In [58]:
print(data.isnull().sum())

ID                       0
Source                   0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
End_Lat                  0
End_Lng                  0
Distance(mi)             0
Description              0
Street                   0
City                     0
County                   0
State                    0
Zipcode                  0
Country                  0
Timezone                 0
Airport_Code             0
Weather_Timestamp        0
Temperature(F)           0
Wind_Chill(F)            0
Humidity(%)              0
Pressure(in)             0
Visibility(mi)           0
Wind_Direction           0
Wind_Speed(mph)          0
Precipitation(in)        0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           0
Civil_Twilight           0
Nautical_Twilight        0
Astronomical_Twilight    0
dtype: int64

In [60]:
data.to_csv('task5_dataset_cleaned.csv', index=False)